apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocspd.fullname" . }}-config
  labels:
    {{- include "ocspd.labels" . | nindent 4 }}
data:
  OCSP_INDEX: '/etc/ocspd/index.txt'
  OCSP_CACERT: '/etc/ocspd/ca.crt'
  OCSP_RESPCERT: '/etc/ocspd/responder.crt'
  OCSP_RESPKEY: '/etc/ocspd/responder.key'
  OCSP_LOGTOSTDOUT: 'true'
